---
title: "Final Project: State Parks"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
#load libraries
library(tidyverse)
library(stringr)
library(rvest)
library(polite)
library(sf)
library(maps)
library(viridis)
library(leaflet)
library(htmltools)
library(janitor)
library(httr)
library(shiny)
library(wordcloud)
library(ggrepel)
```

Introduction
=================

```{r, echo = FALSE}
#function to scrape
scrape_parks <- function(url) {
  Sys.sleep(0.5)
  session <- bow(url)
  scrape(session) |>
    html_nodes("#parklink") |>
    html_text()
}

#scrape the websites
ga_parks <- scrape_parks("https://stateparks.com/ga.html")
mn_parks <- scrape_parks("https://stateparks.com/mn.html")
wi_parks <- scrape_parks("https://stateparks.com/wi.html")
ia_parks <- scrape_parks("https://stateparks.com/ia.html")
ca_parks <- scrape_parks("https://stateparks.com/ca.html")
ut_parks <- scrape_parks("https://stateparks.com/ut.html")
wa_parks <- scrape_parks("https://stateparks.com/wa.html")
me_parks <- scrape_parks("https://stateparks.com/me.html")
az_parks <- scrape_parks("https://stateparks.com/az.html")
sd_parks <- scrape_parks("https://stateparks.com/sd.html")
nd_parks <- scrape_parks("https://stateparks.com/nd.html")
ne_parks <- scrape_parks("https://stateparks.com/ne.html")
mi_parks <- scrape_parks("https://stateparks.com/mi.html")
ks_parks <- scrape_parks("https://stateparks.com/ks.html")
la_parks <- scrape_parks("https://stateparks.com/la.html")
ms_parks <- scrape_parks("https://stateparks.com/ms.html")
mo_parks <- scrape_parks("https://stateparks.com/mo.html")
il_parks <- scrape_parks("https://stateparks.com/il.html")
co_parks <- scrape_parks("https://stateparks.com/co.html")
ny_parks <- scrape_parks("https://stateparks.com/ny.html")

#function for tibble creation
state_tibble <- function(state_name, state_parks) {
  tib <- as_tibble(state_parks)
  tib$state <- state_name
  return(tib)
}

#labeling
ga_tib <- state_tibble("Georgia", ga_parks)
mn_tib <- state_tibble("Minnesota", mn_parks)
wi_tib <- state_tibble("Wisconsin", wi_parks) 
ia_tib <- state_tibble("Iowa", ia_parks)
ca_tib <- state_tibble("California", ca_parks)
ut_tib <- state_tibble("Utah", ut_parks)
wa_tib <- state_tibble("Washington", wa_parks)
me_tib <- state_tibble("Maine", me_parks)
az_tib <- state_tibble("Arizona", az_parks)
sd_tib <- state_tibble("South Dakota", sd_parks)
nd_tib <- state_tibble("North Dakota", nd_parks)
ne_tib <- state_tibble("Nebraska", ne_parks)
mi_tib <- state_tibble("Michigan", mi_parks)
ks_tib <- state_tibble("Kansas", ks_parks)
la_tib <- state_tibble("Louisiana", la_parks)
ms_tib <- state_tibble("Mississippi", ms_parks)
mo_tib <- state_tibble("Missouri", mo_parks)
il_tib <- state_tibble("Illinois", il_parks)
co_tib <- state_tibble("Colorado", co_parks)
ny_tib <- state_tibble("New York", ny_parks)

#parks data cleaning
midwest_parks <- mn_tib |>
  bind_rows(wi_tib, ia_tib, sd_tib, nd_tib, ne_tib, mo_tib, il_tib, mi_tib, ks_tib) |>
  rename(park = value)


full_parks <- ga_tib |>
  bind_rows(mn_tib, wi_tib, ia_tib, ca_tib, ut_tib, wa_tib, me_tib, az_tib, sd_tib, nd_tib, ne_tib, co_tib, il_tib, ks_tib, la_tib, mi_tib, mo_tib, ms_tib, ny_tib) |>
  rename(park = value)
```


```{r, include=FALSE}
#check URL for permission
robotstxt::paths_allowed("https://worldpopulationreview.com/state-rankings/air-quality-by-state")

#web scraping session beginning
session <- bow("https://worldpopulationreview.com/state-rankings/air-quality-by-state", force = TRUE)

#scrape the content, extract and convert
air_result <- scrape(session) |>
  html_nodes(css = "table") |>
  html_table(header = TRUE, fill = TRUE)

air_result
```

```{r, include=FALSE}
air_quality <- air_result[[1]] |>
  select(State, `Air Quality Index↓`, `Air Quality Rank (US News 2024)`, `Days with Unhealthy Air Quality (US News 2024)`, `Industrial Toxin Concentration (US News 2024) (pounds/mi²)`) |>
  rename(air_quality_index = `Air Quality Index↓`,
         air_quality_rank = `Air Quality Rank (US News 2024)`,
         unhealt_days = `Days with Unhealthy Air Quality (US News 2024)`,
         toxin_concentration = `Industrial Toxin Concentration (US News 2024) (pounds/mi²)`) |>
  filter(!State %in% c("Alaska", "Hawaii", "District of Columbia")) |>
  mutate(toxin_concentration = parse_number(toxin_concentration))

air_quality
```

```{r, include=FALSE}
#check URL for permission
robotstxt::paths_allowed("https://worldpopulationreview.com/states#most-and-least-populous-states")

#web scraping session beginning
session <- bow("https://worldpopulationreview.com/states#most-and-least-populous-states", force = TRUE)

#scrape the content, extract and convert
pop_result <- scrape(session) |>
  html_nodes(css = "table") |>
  html_table(header = TRUE, fill = TRUE)

pop_result
```

```{r, include=FALSE}
#population dataset
population <- pop_result[[1]] |>
  select(State, `2025 Pop.  ↓`, Change, Density) |>
  rename(population =`2025 Pop.  ↓`,
         change = Change,
         density = Density) |>
  mutate(population = parse_number(population),
         pop_density = parse_number(density))
```



State Parks
==================


Row
---------------------------
```{r, echo=FALSE}
inputPanel(
  selectInput("stateInput", label = "Select State",
              choices = c("Illinois", "Iowa", "Kansas", "Michigan", "Minnesota", "Missouri", "Nebraska", "North Dakota", "South Dakota", "Wisconsin"), 
              selected = "Minnesota"), #state dropdown
  
  selectInput("parkInput", label = "Select Type of Park",
              choices = c("National Park", "National Forest", "State Park", "State Forest", "National Wildlife Refuge"), 
              selected = "State Park") #park types dropdown
)
```


```{r, echo = FALSE}
#creating wordcloud based on total number of parks
num_parks <- full_parks |>
  count(state)

wordcloud(
  words = num_parks$state, 
  freq = num_parks$n, 
  max.words = 50, 
  random.order = FALSE, 
  rot.per = 0.35,
  scale = c(5, 0.25),
  colors = brewer.pal(6, "Dark2"))
```

In this Wordcloud, the size of the words correlates with how many state parks each state has. 

Row
------------------------
```{r, echo=FALSE}

renderPlot({
  state_park_types <- midwest_parks |>
  filter(state == input$stateInput) |>
  mutate(type_park = str_extract(park, "State Forest|State Park|National Park|National Forest|National Wildlife Refuge"), #separating into different types of parks variable
         type_park = replace_na(type_park, "Other")) |>
  count(type_park)
  ggplot(state_park_types, aes(x = type_park, y = n, fill = type_park)) +
    geom_bar(stat = "identity") +
    theme_classic() +
    scale_fill_viridis(discrete = TRUE, option = "G") +
    labs(title = paste("Number of Parks in", input$stateInput),
         x = "Type of Park",
         y = "Number of Parks",
         fill = "Type of Park")
})
```

```{r, echo=FALSE}

renderPlot({
  state_park_types <- midwest_parks |>
  mutate(type_park = str_extract(park, "State Forest|State Park|National Park|National Forest|National Wildlife Refuge"), 
         type_park = replace_na(type_park, "Other")) |>
  filter(type_park == input$parkInput) |>
  group_by(state) |>
  count(type_park)
  ggplot(state_park_types, aes(x = state, y = n, fill = type_park)) +
    geom_bar(stat = "identity", fill = "forestgreen", color = "black") +
    theme_classic() +
    labs(title = paste(input$parkInput, "Counts in Each State of the Midwest"),
         x = "State",
         y = "Number of Parks",
         fill = "Type of Park")
  
})

```



Air Quality
=================


```{r, echo=FALSE}
state_sf <- read_sf("https://rstudio.github.io/leaflet/json/us-states.geojson") |>
  rename(State = name)


state_air <- right_join(state_sf, air_quality, by ="State")


bins <-  c(35, 40, 45, 50, Inf)
pal <- colorBin("Greens", domain = state_sf$density, bins = bins)

#Hover labels
state_air <- state_air |>
  mutate(State = str_to_title(State)) |>
  mutate(labels = str_c(State, ": ", round(air_quality_index,2), " AQI (0 = great)"))

labels <- lapply(state_air$labels, HTML)

#creation of interactive plot
leaflet(state_air) |>
  setView(-96, 37.8, 3.5) |> #set initial view
  addTiles() |>
  addPolygons( #polygons for each state
    dashArray = "",
    fillColor = ~colorNumeric("Greens", domain = state_air$air_quality_index)(state_air$air_quality_index),
    weight = 3,
    opacity = 2,
    color = "white",
    fillOpacity = 0.8,
    highlightOptions = highlightOptions( #add highlight while hovering
      weight = 4,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions( #label appearance
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")) |>
  addLegend(pal = pal,
            values = ~air_quality_index, 
            opacity = 0.7, 
            title = NULL, 
            position = "bottomright")
```


Air Quality and Population
=================


```{r, echo=FALSE, message=FALSE}
pop_air <- air_quality |>
  left_join(population, by = "State")
```


```{r, echo=FALSE, message=FALSE}
ui <- fluidPage(
  titlePanel("Population and Environmental Impact"), #title
  inputPanel( #drop down menu
  selectInput("impactInput", label = "Select Impact Variable:",
    choices = c("Toxin Concentration (lbs//mi²)" = "toxin_concentration", #"choice name" = "actual variable name"
                "Unhealthy Days in 2024" = "unhealt_days",
                "Population (2025)" = "population",
                "Population Density" = "pop_density"))),
  leafletOutput("ourmap")) #output for interactive map
```

```{r, echo=FALSE, message=FALSE}
bins <- 5 #number of bins for color scheme

state_sf <- read_sf("https://rstudio.github.io/leaflet/json/us-states.geojson") |> rename(State = name) #states dataset and rename to match our datasets

server <- function(input, output, session) {
  state_air_pop <- right_join(state_sf, pop_air, by ="State") #join by state
  
  #what map should render depending on selected variable
  output$ourmap <- renderLeaflet({
    impact_variable <- input$impactInput #variable from dropdown
    label_text <- ifelse(impact_variable == "toxin_concentration", "Toxin Concentration",
                         ifelse(impact_variable == "unhealt_days", "Unhealthy Days in 2025",
                                ifelse(impact_variable == "population", "Population in 2025",
                                       ifelse(impact_variable == "pop_density", "Population Density", ""))))
    pal <- colorBin("RdYlBl", domain = state_air_pop[[impact_variable]], bins = bins) 
    labels <- str_c(state_air_pop$State, "'s ", label_text, ": ", round(state_air_pop[[impact_variable]],2))


    
    #creation of interactive plot
leaflet(state_air_pop) |>
  setView(-96, 37.8, 3.5) |> #set initial view
  addTiles() |>
  addPolygons( #polygons for each state
    dashArray = "",
    fillColor = ~colorNumeric("Blues", domain = state_air_pop[[impact_variable]])(state_air_pop[[impact_variable]]),
    weight = 3,
    opacity = 0.8,
    color = "white",
    fillOpacity = 0.8,
    highlightOptions = highlightOptions( #add highlight while hovering
      weight = 4,
      color = "black",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = ~lapply(labels, HTML),
    labelOptions = labelOptions( #label appearance
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")) |>
  addLegend(pal = pal,
            values = state_air_pop[[impact_variable]], 
            opacity = 0.7, 
            title = input$impactInput, 
            position = "bottomright")})
}

#launch shiny app with ui and server
shinyApp(ui, server)
```




State Parks, Air Quality, and Population
===========================

Inputs {.sidebar}
----------------------

```{r, echo=FALSE}
inputPanel(
  selectInput("airquality", label = "Air Quality Variable",
              choices = c("Air Quality Index" = "air_quality_index", "Unhealthy Days in 2024" = "unhealt_days", "Toxin Concentration (lbs//mi²)" = "toxin_concentration")), #new names for drop down
  
  selectInput("population", label = "Population Variable",
              choices = c("Population (2025)" = "population", "Population Density" = "pop_density", "% Change in Population" = "change_numeric")), #new names for drop down
  checkboxInput("check_line", "Include Trend Line?", value = FALSE)
)

```


Row
----------------------

```{r, echo=FALSE}

renderPlot({
park_air <- full_parks |>
    group_by(state) |>
    summarize(num_parks = n()) |>
    left_join(air_quality, by = c("state" = "State")) #join with air quality
labels <- c("air_quality_index" = "Air Quality Index", "unhealt_days" = "Unhealthy Days in 2024", "toxin_concentration" = "Toxin Concentration (lbs//mi²)") #creating labels for the plot
selected_label <- labels[input$airquality]
if(input$check_line)
  ggplot(park_air, aes(x = num_parks, y = .data[[input$airquality]])) +
    geom_point(color = "forestgreen") +
    geom_smooth(method = "lm", se = FALSE, color = "red") +
    geom_text_repel(aes(label = state)) + #labeling by state
    labs(title = paste(selected_label, "and Number of Parks per State"),
         x = "Number of Parks",
         y = selected_label)
else if (!input$check_line)
  ggplot(park_air, aes(x = num_parks, y = .data[[input$airquality]])) +
    geom_point(color = "forestgreen") +
    geom_text_repel(aes(label = state)) + #labeling by state
    labs(title = paste(selected_label, "and Number of Parks per State"),
         x = "Number of Parks",
         y = selected_label)
})
```

```{r, echo=FALSE}
renderPlot({
parks_pop <- full_parks |>
    group_by(state) |>
    summarize(num_parks = n()) |>
    left_join(population, by = c("state" = "State")) |> #join with population
    mutate(change_numeric = parse_number(change))
    labels <- c("population" = "Population (2025)", "pop_density" = "Population Density", "change_numeric" = "% Change in Population") #creating labels for the plot
selected_label <- labels[input$population]
if(input$check_line)
  ggplot(parks_pop, aes(x = num_parks, y = .data[[input$population]])) +
    geom_point(color = "forestgreen") +
    geom_text_repel(aes(label = state)) + #labeling by state
    geom_smooth(method = "lm", se = FALSE, color = "red") +
    labs(title = paste(selected_label, "and Number of Parks per State"),
         x = "Number of Parks",
         y = selected_label)
else if(!input$check_line)
  ggplot(parks_pop, aes(x = num_parks, y = .data[[input$population]])) +
    geom_point(color = "forestgreen") +
    geom_text_repel(aes(label = state)) + #labeling by state
    labs(title = paste(selected_label, "and Number of Parks per State"),
         x = "Number of Parks",
         y = selected_label)
})
```



Conclusion
==================


Works Cited:
Cheng, J., Schloerke, B., Karambelkar, B., Xie, Y., & Posit. (n.d.). Using Leaflet with Shiny. RStudio. Retrieved May 12, 2025, from https://rstudio.github.io/leaflet/articles/shiny.html
